# Generated by Django 5.2.9 on 2026-01-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='assigned_authority',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='feedback_comment',
        ),
        migrations.AddField(
            model_name='grievance',
            name='current_handler_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='department_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile'),
        ),
    ]
