# Generated by Django 5.2.9 on 2026-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_grievance_assigned_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_imgs/'),
        ),
    ]
