# Generated by Django 5.2.9 on 2026-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grievance_resolved_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('auto_escalation', models.BooleanField(default=False)),
                ('email_alerts', models.BooleanField(default=True)),
            ],
        ),
    ]
